plugins { kotlin("jvm") }

kotlin { jvmToolchain(21) }

dependencies {
    testImplementation(kotlin("test-junit"))
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
}

tasks.test {
    useJUnit()
    val gatewaySubmissionVectors = rootProject.layout.projectDirectory.file("protocol/vectors/gateway-submission-v1.json")
    inputs.file(gatewaySubmissionVectors)
    systemProperty("remozio.gatewaySubmissionVectors", gatewaySubmissionVectors.asFile.absolutePath)
    val pairingVectors = rootProject.layout.projectDirectory.file("protocol/vectors/pairing-v1.json")
    inputs.file(pairingVectors)
    systemProperty("remozio.pairingVectors", pairingVectors.asFile.absolutePath)
    val channelVectors = rootProject.layout.projectDirectory.file("protocol/vectors/channel-negotiation-v1.json")
    inputs.file(channelVectors)
    systemProperty("remozio.channelVectors", channelVectors.asFile.absolutePath)
    val routingVectors = rootProject.layout.projectDirectory.file("protocol/vectors/routing-away-v1.json")
    inputs.file(routingVectors)
    systemProperty("remozio.routingVectors", routingVectors.asFile.absolutePath)
    val pushDataVectors = rootProject.layout.projectDirectory.file("protocol/vectors/push-data-v1.json")
    inputs.file(pushDataVectors)
    systemProperty("remozio.pushDataVectors", pushDataVectors.asFile.absolutePath)
    val gatewayRecipientVectors = rootProject.layout.projectDirectory.file("protocol/vectors/gateway-recipient-v1.json")
    inputs.file(gatewayRecipientVectors)
    systemProperty("remozio.gatewayRecipientVectors", gatewayRecipientVectors.asFile.absolutePath)
    val gatewayTokenVectors = rootProject.layout.projectDirectory.file("protocol/vectors/gateway-token-v1.json")
    inputs.file(gatewayTokenVectors)
    systemProperty("remozio.gatewayTokenVectors", gatewayTokenVectors.asFile.absolutePath)
    val auditHistoryVectors = rootProject.layout.projectDirectory.file("protocol/vectors/audit-history-status-v1.json")
    inputs.file(auditHistoryVectors)
    systemProperty("remozio.auditHistoryVectors", auditHistoryVectors.asFile.absolutePath)
    val auditBatchVectors = rootProject.layout.projectDirectory.file("protocol/vectors/audit-batches-v1.json")
    inputs.file(auditBatchVectors)
    systemProperty("remozio.auditBatchVectors", auditBatchVectors.asFile.absolutePath)
    val auditVectors = rootProject.layout.projectDirectory.file("protocol/vectors/audit-metadata-v1.json")
    inputs.file(auditVectors)
    systemProperty("remozio.auditVectors", auditVectors.asFile.absolutePath)
    val vectors = rootProject.layout.projectDirectory.file("protocol/vectors/cbor-subset-v1.json")
    val actionVectors = rootProject.layout.projectDirectory.file("protocol/vectors/action-policy-v1.json")
    val lifecycleVectors = rootProject.layout.projectDirectory.file("protocol/vectors/lifecycle-v1.json")
    val signingVectors = rootProject.layout.projectDirectory.file("protocol/vectors/signing-input-v1.json")
    val signatureVectors = rootProject.layout.projectDirectory.file("protocol/vectors/approval-signatures-v1.json")
    val decisionVectors = rootProject.layout.projectDirectory.file("protocol/vectors/decision-payload-v1.json")
    val requestVectors = rootProject.layout.projectDirectory.file("protocol/vectors/issued-request-v1.json")
    val statusVectors = rootProject.layout.projectDirectory.file("protocol/vectors/request-status-v1.json")
    systemProperty("remozio.statusVectors", statusVectors.asFile.absolutePath)
    val commandVectors = rootProject.layout.projectDirectory.file("protocol/vectors/command-capture-v1.json")
    systemProperty("remozio.commandVectors", commandVectors.asFile.absolutePath)
    val commandVectors2 = rootProject.layout.projectDirectory.file("protocol/vectors/command-capture-v2.json")
    systemProperty("remozio.commandVectors2", commandVectors2.asFile.absolutePath)
    val commandVectors3 = rootProject.layout.projectDirectory.file("protocol/vectors/command-capture-v3.json")
    systemProperty("remozio.commandVectors3", commandVectors3.asFile.absolutePath)
    inputs.files(commandVectors3, commandVectors2, statusVectors, commandVectors, vectors, actionVectors, lifecycleVectors, signingVectors, signatureVectors, decisionVectors, requestVectors)
    systemProperty("remozio.requestVectors", requestVectors.asFile.absolutePath)
    systemProperty("remozio.decisionVectors", decisionVectors.asFile.absolutePath)
    systemProperty("remozio.signatureVectors", signatureVectors.asFile.absolutePath)
    systemProperty("remozio.signingVectors", signingVectors.asFile.absolutePath)
    systemProperty("remozio.lifecycleVectors", lifecycleVectors.asFile.absolutePath)
    systemProperty("remozio.actionVectors", actionVectors.asFile.absolutePath)
    systemProperty("remozio.vectors", vectors.asFile.absolutePath)
}
